-- Fase 5.3 — baseline do Flyway. O banco de produção já existia havia
-- meses gerenciado por `ddl-auto: update` (Hibernate criando/ajustando
-- schema sozinho) quando o Flyway entrou — por isso essa migração NÃO
-- roda contra ele: spring.flyway.baseline-on-migrate marca esse banco
-- como "já na versão 1" sem executar nada aqui. O conteúdo real (gerado
-- via `pg_dump --schema-only` em cima do banco de produção real) existe
-- pra dois casos: (1) documentação de como o schema estava nesse ponto,
-- e (2) reprodutibilidade de verdade — um banco novo/vazio (dev local,
-- CI, um ambiente novo) RODA este script normalmente e termina no mesmo
-- estado. Daqui pra frente, toda mudança de schema é um V2__, V3__, etc.
-- novo — não editar este arquivo depois de aplicado.
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: gmail_tokens; Type: TABLE; Schema: public; Owner: jobradar
--

CREATE TABLE public.gmail_tokens (
    id bigint NOT NULL,
    access_token text,
    access_token_expires_at timestamp(6) without time zone,
    connected_at timestamp(6) without time zone,
    email_address character varying(255),
    refresh_token text NOT NULL
);


ALTER TABLE public.gmail_tokens OWNER TO jobradar;

--
-- Name: job_embeddings; Type: TABLE; Schema: public; Owner: jobradar
--

CREATE TABLE public.job_embeddings (
    id bigint NOT NULL,
    vector bytea NOT NULL
);


ALTER TABLE public.job_embeddings OWNER TO jobradar;

--
-- Name: job_events; Type: TABLE; Schema: public; Owner: jobradar
--

CREATE TABLE public.job_events (
    id bigint NOT NULL,
    occurred_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    job_id bigint NOT NULL
);


ALTER TABLE public.job_events OWNER TO jobradar;

--
-- Name: job_events_id_seq; Type: SEQUENCE; Schema: public; Owner: jobradar
--

ALTER TABLE public.job_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: jobradar
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    applied boolean NOT NULL,
    company character varying(255) NOT NULL,
    fetched_at timestamp(6) without time zone,
    posted_at timestamp(6) without time zone,
    salary character varying(255),
    seen boolean NOT NULL,
    source character varying(255) NOT NULL,
    tags text,
    title character varying(255) NOT NULL,
    url character varying(1000) NOT NULL,
    expires_at date,
    seniority character varying(255),
    city character varying(255),
    state character varying(255),
    workplace_type character varying(255),
    in_progress boolean DEFAULT false NOT NULL,
    rejected boolean DEFAULT false NOT NULL,
    rejected_at timestamp without time zone,
    company_logo_url character varying(500),
    favorited boolean,
    notes text,
    pcd boolean,
    applied_at timestamp(6) without time zone,
    in_progress_at timestamp(6) without time zone,
    interested boolean DEFAULT false NOT NULL,
    classified_by_ai boolean,
    salary_checked_at timestamp(6) without time zone
);


ALTER TABLE public.jobs OWNER TO jobradar;

--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: jobradar
--

ALTER TABLE public.jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: weekly_digests; Type: TABLE; Schema: public; Owner: jobradar
--

CREATE TABLE public.weekly_digests (
    id bigint NOT NULL,
    conteudo text NOT NULL,
    gerado_em timestamp(6) without time zone,
    prazos_proximos integer NOT NULL,
    vagas_novas integer NOT NULL,
    vagas_paradas integer NOT NULL
);


ALTER TABLE public.weekly_digests OWNER TO jobradar;

--
-- Name: gmail_tokens gmail_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: jobradar
--

ALTER TABLE ONLY public.gmail_tokens
    ADD CONSTRAINT gmail_tokens_pkey PRIMARY KEY (id);


--
-- Name: job_embeddings job_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: jobradar
--

ALTER TABLE ONLY public.job_embeddings
    ADD CONSTRAINT job_embeddings_pkey PRIMARY KEY (id);


--
-- Name: job_events job_events_pkey; Type: CONSTRAINT; Schema: public; Owner: jobradar
--

ALTER TABLE ONLY public.job_events
    ADD CONSTRAINT job_events_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: jobradar
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: jobs uk38e87352dtj1f3hir9eh2makb; Type: CONSTRAINT; Schema: public; Owner: jobradar
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT uk38e87352dtj1f3hir9eh2makb UNIQUE (url);


--
-- Name: weekly_digests weekly_digests_pkey; Type: CONSTRAINT; Schema: public; Owner: jobradar
--

ALTER TABLE ONLY public.weekly_digests
    ADD CONSTRAINT weekly_digests_pkey PRIMARY KEY (id);


--
-- Name: idx_jobs_expires_at; Type: INDEX; Schema: public; Owner: jobradar
--

CREATE INDEX idx_jobs_expires_at ON public.jobs USING btree (expires_at);


--
-- Name: idx_jobs_posted_at; Type: INDEX; Schema: public; Owner: jobradar
--

CREATE INDEX idx_jobs_posted_at ON public.jobs USING btree (posted_at);


--
-- Name: idx_jobs_seen_rejected; Type: INDEX; Schema: public; Owner: jobradar
--

CREATE INDEX idx_jobs_seen_rejected ON public.jobs USING btree (seen, rejected);


--
-- Name: idx_jobs_source; Type: INDEX; Schema: public; Owner: jobradar
--

CREATE INDEX idx_jobs_source ON public.jobs USING btree (source);


--
-- Name: idx_jobs_state; Type: INDEX; Schema: public; Owner: jobradar
--

CREATE INDEX idx_jobs_state ON public.jobs USING btree (state);


--
-- Name: job_events fko0m445mx7q8ur5lcdytqumkg2; Type: FK CONSTRAINT; Schema: public; Owner: jobradar
--

ALTER TABLE ONLY public.job_events
    ADD CONSTRAINT fko0m445mx7q8ur5lcdytqumkg2 FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- PostgreSQL database dump complete
--


